### PR TITLE
add multicore merlin and dot-merlin-reader

### PR DESCRIPTION
**Pull request by mattpallissard**
Patch merlin and dot-merlin-reader to work with the ocaml 4.10 multicore fork.

### CODE REVIEW

**Comment by mattpallissard** [comment]
My apologies for all of the force-pushes.  I mistakenly thought that I had opened this PR from a feature branch, not my dev one.

**Review by Sudha247 — APPROVED** [review]
Thank you @mattpallissard! This one is good to go. I have tested it with `parallel_minor_gc` and `no-effect-syntax`, it works well on both.

**Comment by mattpallissard** [comment]
@Sudha247 that's great.  Can you merge it? Or do we have to add another participant?

**Comment by Sudha247** [comment]
Sorry for the delay. We were discussing offline whether to hold the patch files here or hold them elsewhere and point the branch from here. Since the patches don't require changes often, makes sense to have them here. Merging. Thanks again!

**Comment by mattpallissard** [comment]
Understood, thanks.  As an aside; if you had a central project you wanted to house the source and ocaml-lsp-server release under I'd be happy to push it all there and modify things accordingly.

For posterity, all the relevant code is below.  

**merlin**
* https://github.com/mattpallissard/merlin/tree/feature/multicore_410

**ocaml-lsp-server**
(which also references a slightly modified branch of merlin)
* https://github.com/mattpallissard/ocaml-lsp/tree/master
* https://github.com/mattpallissard/merlin/tree/feature/lsp

**Pull request merged**
