### PR TITLE
Remove dune and ocaml-secondary-compiler dependencies

### PR DESCRIPTION
**Pull request by shakthimaan**
With the re-implementation of systhreads with pthreads (https://github.com/ocaml-multicore/ocaml-multicore/pull/381), and being able to build dune natively (without requiring the dune symbolic link system hack), we can remove `dune` and `ocaml-secondary-compiler` dependency.

The following steps can be used to test the PR:
```
$ opam update
$ opam compiler create "ocaml-multicore/ocaml-multicore:no-effect-syntax"
```
The output of `opam switch`:
```
#  switch                                            compiler                    description
   4.10.0                                            ocaml-base-compiler.4.10.0  4.10.0
→  ocaml-multicore-ocaml-multicore-no-effect-syntax                              [opam-compiler] ocaml-multicore/ocaml-multicore:no-effect-syntax
```
We can proceed to install dune natively, and add this test repository that does not require `dune` and `ocaml-secondary-compiler`:
```
$ opam install dune.2.7.1
$ opam repository add multicore git+https://github.com/shakthimaan/multicore-opam#build/remove-secondary-compiler
```
You can verify the same, and install the Multicore libraries:
```
$ opam repository
...
 1 multicore git+https://github.com/shakthimaan/multicore-opam#build/remove-secondary-compiler
 2 default   https://opam.ocaml.org

$ opam install lockfree
$ opam install domainslib
```

### CODE REVIEW

**Comment by kayceesrk** [comment]
Thanks for this @shakthimaan. Your test is using `no-effect-syntax` branch. Is this necessary? Will these steps not work on the default branch `parallel_minor_gc`?

**Comment by shakthimaan** [comment]
We require that the systhreads PR implementation using pthreads be merged to the respective branch, so that dune can be built natively using the same. 
1. CMIIW, the `no-effect-syntax` branch is the one that gets all the latest updates and PRs? 
2. Any reason to continue to use the `parallel_minor_gc` branch? It has been merged (https://github.com/ocaml-multicore/ocaml-multicore/pull/444) to the no-effect-syntax branch.

**Comment by kayceesrk** [comment]
`parallel_minor_gc` is the default branch. `no-effect-syntax` is `parallel_minor_gc` - effect syntax in order to circumvent ppx breakage. For the multicore team and academic researchers, `parallel_minor_gc` is the interesting branch. For the ecosystem questions, i.e, how many packages can we build without breaking, `no-effect-syntax` is used. 

All the changes are proposed against `parallel_minor_gc`. `no-effect-syntax` plays catch up. 

> We require that the systhreads PR implementation using pthreads be merged to the respective branch, so that dune can be built natively using the same.

I don't understand this. systhreads are already merged.

**Comment by kayceesrk** [comment]
See also the README.md file in ocaml-multicore https://github.com/ocaml-multicore/ocaml-multicore#variants, which mentions `parallel_minor_gc` as the default branch.

**Comment by shakthimaan** [comment]
> All the changes are proposed against parallel_minor_gc. no-effect-syntax plays catch up.

I now see how the branch merges occur. Thanks!

> systhreads are already merged.

Okay. I see it got merged to parallel_minor_gc https://github.com/ocaml-multicore/ocaml-multicore/pull/407.

> Will these steps not work on the default branch parallel_minor_gc

Yes, it works fine for the `parallel_minor_gc`, and I am able to install dune natively, without requiring it to be pulled from multicore-opam repository. 
```
$  opam switch
#  switch                                            compiler                    description
→  4.10.0                                            ocaml-base-compiler.4.10.0  4.10.0
   default                                           ocaml-system.4.11.1         default
   ocaml-multicore-ocaml-multicore-no-effect-syntax                              [opam-compiler] ocaml-multicore/ocaml-multicore:no-effect-syntax
```
Creating a new switch environment:
```
$  opam compiler create "ocaml-multicore/ocaml-multicore:parallel_minor_gc"
$  opam switch
#  switch                                             compiler                    description
   4.10.0                                             ocaml-base-compiler.4.10.0  4.10.0
   default                                            ocaml-system.4.11.1         default
   ocaml-multicore-ocaml-multicore-no-effect-syntax                               [opam-compiler] ocaml-multicore/ocaml-multicore:no-effect-syntax
→  ocaml-multicore-ocaml-multicore-parallel_minor_gc                              [opam-compiler] ocaml-multicore/ocaml-multicore:parallel_minor_gc
```
Install dune.2.7.1 natively (not the one from multicore-opam):
```
$  opam install dune.2.7.1

$  opam list
# Packages matching: installed
# Name         # Installed      # Synopsis
base-bigarray  base
base-threads   base
base-unix      base
dune           2.7.1            Fast, portable, and opinionated build system
ocaml          4.10.0           The OCaml compiler (virtual package)
ocaml-config   1                OCaml Switch Configuration
ocaml-variants 4.10.0+multicore pinned to version 4.10.0+multicore at git+https://github.com/ocaml-multicore/ocaml-multicore#parallel_minor_gc
```
Add multicore-opam repository with this PR patch:
```
$ opam repository add multicore git+https://github.com/shakthimaan/multicore-opam#build/remove-secondary-compiler
$ opam repository
...
<><> Repository configuration for switch ocaml-multicore-ocaml-multicore-parallel_minor_gc 
 1 multicore git+https://github.com/shakthimaan/multicore-opam#build/remove-secondary-compiler
 2 default   https://opam.ocaml.org

$  opam install lockfree
$  opam install domainslib
```
Hence, this PR to remove dune and ocaml-secondary-compiler from multicore-opam repository. The only remaining question is are there any downstream users who still require to use `ocaml-secondary-compiler`?

**Comment by kayceesrk** [comment]
I believe that `dune` was the only user of `ocaml-secondary-compiler`. If you fix the conflict, we can merge the PR.

**Pull request merged**
